project_id = "zawkhtkyaucsrhqqlviv"

[functions.admin-create-user]
verify_jwt = true

[functions.team-create-member]
verify_jwt = true

[functions.property-market-analysis]
verify_jwt = false

[functions.team-update-member]
verify_jwt = true
