project_id = "zawkhtkyaucsrhqqlviv"

[functions.admin-create-user]
verify_jwt = true

[functions.team-create-member]
verify_jwt = true

[functions.property-market-analysis]
verify_jwt = true

[functions.team-update-member]
verify_jwt = true

[functions.parse-self-disclosure]
verify_jwt = true

[functions.property-macro-location]
verify_jwt = true
