/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as OaaxRouteImport } from './routes/oaax'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SelbstauskunftTokenRouteImport } from './routes/selbstauskunft.$token'
import { Route as FinanzierungTokenRouteImport } from './routes/finanzierung.$token'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReservationsRouteImport } from './routes/_app/reservations'
import { Route as AppMediaRouteImport } from './routes/_app/media'
import { Route as AppMatchingRouteImport } from './routes/_app/matching'
import { Route as AppMandatesRouteImport } from './routes/_app/mandates'
import { Route as AppLeadsRouteImport } from './routes/_app/leads'
import { Route as AppExposesRouteImport } from './routes/_app/exposes'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppChecklistsRouteImport } from './routes/_app/checklists'
import { Route as AppAppointmentsRouteImport } from './routes/_app/appointments'
import { Route as AppPropertiesIndexRouteImport } from './routes/_app/properties.index'
import { Route as AppLeadsIndexRouteImport } from './routes/_app/leads.index'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients.index'
import { Route as AppPropertiesIdRouteImport } from './routes/_app/properties.$id'
import { Route as AppLeadsIdRouteImport } from './routes/_app/leads.$id'
import { Route as AppClientsIdRouteImport } from './routes/_app/clients.$id'
import { Route as AppPropertiesIdExposeRouteImport } from './routes/_app/properties.$id.expose'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OaaxRoute = OaaxRouteImport.update({
  id: '/oaax',
  path: '/oaax',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelbstauskunftTokenRoute = SelbstauskunftTokenRouteImport.update({
  id: '/selbstauskunft/$token',
  path: '/selbstauskunft/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzierungTokenRoute = FinanzierungTokenRouteImport.update({
  id: '/finanzierung/$token',
  path: '/finanzierung/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchingRoute = AppMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => AppRoute,
} as any)
const AppMandatesRoute = AppMandatesRouteImport.update({
  id: '/mandates',
  path: '/mandates',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppExposesRoute = AppExposesRouteImport.update({
  id: '/exposes',
  path: '/exposes',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppChecklistsRoute = AppChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesIndexRoute = AppPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppPropertiesIdRoute = AppPropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIdRoute = AppLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppPropertiesIdExposeRoute = AppPropertiesIdExposeRouteImport.update({
  id: '/expose',
  path: '/expose',
  getParentRoute: () => AppPropertiesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/oaax': typeof OaaxRoute
  '/set-password': typeof SetPasswordRoute
  '/appointments': typeof AppAppointmentsRoute
  '/checklists': typeof AppChecklistsRoute
  '/clients': typeof AppClientsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/exposes': typeof AppExposesRoute
  '/leads': typeof AppLeadsRouteWithChildren
  '/mandates': typeof AppMandatesRoute
  '/matching': typeof AppMatchingRoute
  '/media': typeof AppMediaRoute
  '/reservations': typeof AppReservationsRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/team': typeof AppTeamRoute
  '/templates': typeof AppTemplatesRoute
  '/finanzierung/$token': typeof FinanzierungTokenRoute
  '/selbstauskunft/$token': typeof SelbstauskunftTokenRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/leads/$id': typeof AppLeadsIdRoute
  '/properties/$id': typeof AppPropertiesIdRouteWithChildren
  '/clients/': typeof AppClientsIndexRoute
  '/leads/': typeof AppLeadsIndexRoute
  '/properties/': typeof AppPropertiesIndexRoute
  '/properties/$id/expose': typeof AppPropertiesIdExposeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/oaax': typeof OaaxRoute
  '/set-password': typeof SetPasswordRoute
  '/appointments': typeof AppAppointmentsRoute
  '/checklists': typeof AppChecklistsRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/exposes': typeof AppExposesRoute
  '/mandates': typeof AppMandatesRoute
  '/matching': typeof AppMatchingRoute
  '/media': typeof AppMediaRoute
  '/reservations': typeof AppReservationsRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/team': typeof AppTeamRoute
  '/templates': typeof AppTemplatesRoute
  '/finanzierung/$token': typeof FinanzierungTokenRoute
  '/selbstauskunft/$token': typeof SelbstauskunftTokenRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/leads/$id': typeof AppLeadsIdRoute
  '/properties/$id': typeof AppPropertiesIdRouteWithChildren
  '/clients': typeof AppClientsIndexRoute
  '/leads': typeof AppLeadsIndexRoute
  '/properties': typeof AppPropertiesIndexRoute
  '/properties/$id/expose': typeof AppPropertiesIdExposeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/oaax': typeof OaaxRoute
  '/set-password': typeof SetPasswordRoute
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/checklists': typeof AppChecklistsRoute
  '/_app/clients': typeof AppClientsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/exposes': typeof AppExposesRoute
  '/_app/leads': typeof AppLeadsRouteWithChildren
  '/_app/mandates': typeof AppMandatesRoute
  '/_app/matching': typeof AppMatchingRoute
  '/_app/media': typeof AppMediaRoute
  '/_app/reservations': typeof AppReservationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/finanzierung/$token': typeof FinanzierungTokenRoute
  '/selbstauskunft/$token': typeof SelbstauskunftTokenRoute
  '/_app/clients/$id': typeof AppClientsIdRoute
  '/_app/leads/$id': typeof AppLeadsIdRoute
  '/_app/properties/$id': typeof AppPropertiesIdRouteWithChildren
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/leads/': typeof AppLeadsIndexRoute
  '/_app/properties/': typeof AppPropertiesIndexRoute
  '/_app/properties/$id/expose': typeof AppPropertiesIdExposeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/oaax'
    | '/set-password'
    | '/appointments'
    | '/checklists'
    | '/clients'
    | '/dashboard'
    | '/documents'
    | '/exposes'
    | '/leads'
    | '/mandates'
    | '/matching'
    | '/media'
    | '/reservations'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/templates'
    | '/finanzierung/$token'
    | '/selbstauskunft/$token'
    | '/clients/$id'
    | '/leads/$id'
    | '/properties/$id'
    | '/clients/'
    | '/leads/'
    | '/properties/'
    | '/properties/$id/expose'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/oaax'
    | '/set-password'
    | '/appointments'
    | '/checklists'
    | '/dashboard'
    | '/documents'
    | '/exposes'
    | '/mandates'
    | '/matching'
    | '/media'
    | '/reservations'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/templates'
    | '/finanzierung/$token'
    | '/selbstauskunft/$token'
    | '/clients/$id'
    | '/leads/$id'
    | '/properties/$id'
    | '/clients'
    | '/leads'
    | '/properties'
    | '/properties/$id/expose'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/oaax'
    | '/set-password'
    | '/_app/appointments'
    | '/_app/checklists'
    | '/_app/clients'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/exposes'
    | '/_app/leads'
    | '/_app/mandates'
    | '/_app/matching'
    | '/_app/media'
    | '/_app/reservations'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/team'
    | '/_app/templates'
    | '/finanzierung/$token'
    | '/selbstauskunft/$token'
    | '/_app/clients/$id'
    | '/_app/leads/$id'
    | '/_app/properties/$id'
    | '/_app/clients/'
    | '/_app/leads/'
    | '/_app/properties/'
    | '/_app/properties/$id/expose'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OaaxRoute: typeof OaaxRoute
  SetPasswordRoute: typeof SetPasswordRoute
  FinanzierungTokenRoute: typeof FinanzierungTokenRoute
  SelbstauskunftTokenRoute: typeof SelbstauskunftTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oaax': {
      id: '/oaax'
      path: '/oaax'
      fullPath: '/oaax'
      preLoaderRoute: typeof OaaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selbstauskunft/$token': {
      id: '/selbstauskunft/$token'
      path: '/selbstauskunft/$token'
      fullPath: '/selbstauskunft/$token'
      preLoaderRoute: typeof SelbstauskunftTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzierung/$token': {
      id: '/finanzierung/$token'
      path: '/finanzierung/$token'
      fullPath: '/finanzierung/$token'
      preLoaderRoute: typeof FinanzierungTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations': {
      id: '/_app/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media': {
      id: '/_app/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matching': {
      id: '/_app/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof AppMatchingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mandates': {
      id: '/_app/mandates'
      path: '/mandates'
      fullPath: '/mandates'
      preLoaderRoute: typeof AppMandatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exposes': {
      id: '/_app/exposes'
      path: '/exposes'
      fullPath: '/exposes'
      preLoaderRoute: typeof AppExposesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checklists': {
      id: '/_app/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof AppChecklistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/properties/': {
      id: '/_app/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AppPropertiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/': {
      id: '/_app/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/_app/properties/$id': {
      id: '/_app/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof AppPropertiesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/$id': {
      id: '/_app/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AppLeadsIdRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/clients/$id': {
      id: '/_app/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/_app/properties/$id/expose': {
      id: '/_app/properties/$id/expose'
      path: '/expose'
      fullPath: '/properties/$id/expose'
      preLoaderRoute: typeof AppPropertiesIdExposeRouteImport
      parentRoute: typeof AppPropertiesIdRoute
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsIdRoute: typeof AppClientsIdRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsIdRoute: AppClientsIdRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppLeadsRouteChildren {
  AppLeadsIdRoute: typeof AppLeadsIdRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsIdRoute: AppLeadsIdRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppPropertiesIdRouteChildren {
  AppPropertiesIdExposeRoute: typeof AppPropertiesIdExposeRoute
}

const AppPropertiesIdRouteChildren: AppPropertiesIdRouteChildren = {
  AppPropertiesIdExposeRoute: AppPropertiesIdExposeRoute,
}

const AppPropertiesIdRouteWithChildren = AppPropertiesIdRoute._addFileChildren(
  AppPropertiesIdRouteChildren,
)

interface AppRouteChildren {
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppChecklistsRoute: typeof AppChecklistsRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppExposesRoute: typeof AppExposesRoute
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppMandatesRoute: typeof AppMandatesRoute
  AppMatchingRoute: typeof AppMatchingRoute
  AppMediaRoute: typeof AppMediaRoute
  AppReservationsRoute: typeof AppReservationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppPropertiesIdRoute: typeof AppPropertiesIdRouteWithChildren
  AppPropertiesIndexRoute: typeof AppPropertiesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppChecklistsRoute: AppChecklistsRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppExposesRoute: AppExposesRoute,
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppMandatesRoute: AppMandatesRoute,
  AppMatchingRoute: AppMatchingRoute,
  AppMediaRoute: AppMediaRoute,
  AppReservationsRoute: AppReservationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTeamRoute: AppTeamRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppPropertiesIdRoute: AppPropertiesIdRouteWithChildren,
  AppPropertiesIndexRoute: AppPropertiesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OaaxRoute: OaaxRoute,
  SetPasswordRoute: SetPasswordRoute,
  FinanzierungTokenRoute: FinanzierungTokenRoute,
  SelbstauskunftTokenRoute: SelbstauskunftTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
