/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as OaaxRouteImport } from './routes/oaax'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinanzierungTokenRouteImport } from './routes/finanzierung.$token'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppMatchingRouteImport } from './routes/_app/matching'
import { Route as AppLeadsRouteImport } from './routes/_app/leads'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppAppointmentsRouteImport } from './routes/_app/appointments'
import { Route as AppPropertiesIndexRouteImport } from './routes/_app/properties.index'
import { Route as AppPropertiesIdRouteImport } from './routes/_app/properties.$id'
import { Route as AppClientsIdRouteImport } from './routes/_app/clients.$id'
import { Route as AppPropertiesIdExposeRouteImport } from './routes/_app/properties.$id.expose'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OaaxRoute = OaaxRouteImport.update({
  id: '/oaax',
  path: '/oaax',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzierungTokenRoute = FinanzierungTokenRouteImport.update({
  id: '/finanzierung/$token',
  path: '/finanzierung/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchingRoute = AppMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesIndexRoute = AppPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesIdRoute = AppPropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppPropertiesIdExposeRoute = AppPropertiesIdExposeRouteImport.update({
  id: '/expose',
  path: '/expose',
  getParentRoute: () => AppPropertiesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/oaax': typeof OaaxRoute
  '/set-password': typeof SetPasswordRoute
  '/appointments': typeof AppAppointmentsRoute
  '/clients': typeof AppClientsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/leads': typeof AppLeadsRoute
  '/matching': typeof AppMatchingRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/finanzierung/$token': typeof FinanzierungTokenRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/properties/$id': typeof AppPropertiesIdRouteWithChildren
  '/properties/': typeof AppPropertiesIndexRoute
  '/properties/$id/expose': typeof AppPropertiesIdExposeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/oaax': typeof OaaxRoute
  '/set-password': typeof SetPasswordRoute
  '/appointments': typeof AppAppointmentsRoute
  '/clients': typeof AppClientsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/leads': typeof AppLeadsRoute
  '/matching': typeof AppMatchingRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/finanzierung/$token': typeof FinanzierungTokenRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/properties/$id': typeof AppPropertiesIdRouteWithChildren
  '/properties': typeof AppPropertiesIndexRoute
  '/properties/$id/expose': typeof AppPropertiesIdExposeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/oaax': typeof OaaxRoute
  '/set-password': typeof SetPasswordRoute
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/clients': typeof AppClientsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/matching': typeof AppMatchingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/finanzierung/$token': typeof FinanzierungTokenRoute
  '/_app/clients/$id': typeof AppClientsIdRoute
  '/_app/properties/$id': typeof AppPropertiesIdRouteWithChildren
  '/_app/properties/': typeof AppPropertiesIndexRoute
  '/_app/properties/$id/expose': typeof AppPropertiesIdExposeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/oaax'
    | '/set-password'
    | '/appointments'
    | '/clients'
    | '/dashboard'
    | '/leads'
    | '/matching'
    | '/settings'
    | '/team'
    | '/finanzierung/$token'
    | '/clients/$id'
    | '/properties/$id'
    | '/properties/'
    | '/properties/$id/expose'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/oaax'
    | '/set-password'
    | '/appointments'
    | '/clients'
    | '/dashboard'
    | '/leads'
    | '/matching'
    | '/settings'
    | '/team'
    | '/finanzierung/$token'
    | '/clients/$id'
    | '/properties/$id'
    | '/properties'
    | '/properties/$id/expose'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/oaax'
    | '/set-password'
    | '/_app/appointments'
    | '/_app/clients'
    | '/_app/dashboard'
    | '/_app/leads'
    | '/_app/matching'
    | '/_app/settings'
    | '/_app/team'
    | '/finanzierung/$token'
    | '/_app/clients/$id'
    | '/_app/properties/$id'
    | '/_app/properties/'
    | '/_app/properties/$id/expose'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OaaxRoute: typeof OaaxRoute
  SetPasswordRoute: typeof SetPasswordRoute
  FinanzierungTokenRoute: typeof FinanzierungTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oaax': {
      id: '/oaax'
      path: '/oaax'
      fullPath: '/oaax'
      preLoaderRoute: typeof OaaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzierung/$token': {
      id: '/finanzierung/$token'
      path: '/finanzierung/$token'
      fullPath: '/finanzierung/$token'
      preLoaderRoute: typeof FinanzierungTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matching': {
      id: '/_app/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof AppMatchingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/properties/': {
      id: '/_app/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AppPropertiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/properties/$id': {
      id: '/_app/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof AppPropertiesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$id': {
      id: '/_app/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/_app/properties/$id/expose': {
      id: '/_app/properties/$id/expose'
      path: '/expose'
      fullPath: '/properties/$id/expose'
      preLoaderRoute: typeof AppPropertiesIdExposeRouteImport
      parentRoute: typeof AppPropertiesIdRoute
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsIdRoute: typeof AppClientsIdRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsIdRoute: AppClientsIdRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppPropertiesIdRouteChildren {
  AppPropertiesIdExposeRoute: typeof AppPropertiesIdExposeRoute
}

const AppPropertiesIdRouteChildren: AppPropertiesIdRouteChildren = {
  AppPropertiesIdExposeRoute: AppPropertiesIdExposeRoute,
}

const AppPropertiesIdRouteWithChildren = AppPropertiesIdRoute._addFileChildren(
  AppPropertiesIdRouteChildren,
)

interface AppRouteChildren {
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMatchingRoute: typeof AppMatchingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppPropertiesIdRoute: typeof AppPropertiesIdRouteWithChildren
  AppPropertiesIndexRoute: typeof AppPropertiesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMatchingRoute: AppMatchingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppPropertiesIdRoute: AppPropertiesIdRouteWithChildren,
  AppPropertiesIndexRoute: AppPropertiesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OaaxRoute: OaaxRoute,
  SetPasswordRoute: SetPasswordRoute,
  FinanzierungTokenRoute: FinanzierungTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
